version: '3'

services:
  api:
    build: .
    ports:
      - 50051:50051
    volumes:
      - ./janken:/go/src/janken
    environment:
      AWS_ACCESS_KEY_ID: 'dummy'
      AWS_SECRET_ACCESS_KEY: 'dummy'
      AWS_DEFAULT_REGION: 'ap-northeast-1'
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
